liip_imagine:
    # Configuration du driver
    driver: 'gd'

    # Configuration des resolvers
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'

    # Configuration des loaders
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    filter_sets:
        # Filtres pour la galerie
        gallery_thumb:
            quality: 85
            filters:
                thumbnail:
                    size: [ 400, 300 ]
                    mode: outbound
                strip: ~

        gallery_medium:
            quality: 90
            filters:
                thumbnail:
                    size: [ 1200, 800 ]
                    mode: inset
                strip: ~

        gallery_large:
            quality: 95
            filters:
                thumbnail:
                    size: [ 1920, 1280 ]
                    mode: inset
                strip: ~

        # Vos filtres existants
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [ 360, 230 ]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [ 800, 530 ]
                    mode: outbound